baseURL: https://docker-setup.dille.io
title: docker-setup
languageCode: en-us
paginate: 5

params:
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName: tools

  # ["orange", "blue", "red", "green", "pink"]
  themeColor: orange

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 0

  # show selector to switch language
  showLanguageSelector: false

  # set theme to full screen width
  fullWidthTheme: false

  # center theme with default width
  centerTheme: false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover: true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated: false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


  twitter:
    # set Twitter handles for Twitter cards
    # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
    # do not include @
    creator: nicholasdille
    #site = ""

languages:
  en:
    languageName: English
    title: docker-setup
    subtitle: The container tools installer and updater
    owner: Nicholas Dille
    #keywords = ""
    #copyright = ""
    menuMore: Show more
    readMore: Show
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page

    params:
      logo:
        logoText: docker-setup
        logoHomeLink: /

    menu:
      main:
      - identifier: browse
        name: Browse
        url: /browse
        pre: <i class='fa fa-heart'></i>
      - identifier: tags
        name: Tags
        url: /tags
  
taxonomies:
  tag: tags
  category: categories

module:
  # In case you would like to make changes to the theme and keep it locally in you repository,
  # uncomment the line below (and correct the local path if necessary).
  # --
  #replacements: "github.com/panr/hugo-theme-terminal -> themes/terminal"
  imports:
  - path: github.com/panr/hugo-theme-terminal
