debug             = false
debug_full        = false
address           = "unix:///run/containerd/containerd.sock"
snapshotter       = "native"
cni_path          = "/usr/local/libexec/cni/bin"
cgroup_manager    = "systemd"
hosts_dir         = ["/etc/containerd/certs.d"]
