name: docker-compose-switch
version: "1.0.5"
check: "" # No dedicated version
platforms:
- linux/amd64
- linux/arm64
flags:
- not-docker-compose-v1
tags:
- org/docker
- standard/docker
- category/default
- container/compose
- type/cli
- lang/go
homepage: https://github.com/docker/compose-switch
description: Replacement to the Compose v1 executable
renovate:
  datasource: github-releases
  package: docker/compose-switch
  extractVersion: ^v(?<version>.+?)$